repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: run-tests
        entry: py.test -v --cov=ep_monitoring
        language: python
        additional_dependencies:
          - pre-commit
          - pytest
          - pytest-cov
        always_run: true
        pass_filenames: false
      - id: isort
        name: sort-dependencies
        entry: isort .
        language: python
        additional_dependencies:
          - isort
        pass_filenames: true
